# Describes the format for available nzbget services

pause:
  name: Pause
  description: Pause download queue.

resume:
  name: Resume
  description: Resume download queue.

set_speed:
  name: Set speed
  description: Set download speed limit
  fields:
    speed:
      name: Speed
      description: Speed limit. 0 is unlimited.
      default: 1000
      selector:
        number:
          min: 0
          max: 1000000
          unit_of_measurement: "kB/s"
