add_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.CREATE_TODO_ITEM
  fields:
    item:
      required: true
      example: "Submit income tax return"
      selector:
        text:
update_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.UPDATE_TODO_ITEM
  fields:
    item:
      required: true
      example: "Submit income tax return"
      selector:
        text:
    rename:
      example: "Something else"
      selector:
        text:
    status:
      example: "needs_action"
      selector:
        select:
          translation_key: status
          options:
            - needs_action
            - completed
remove_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.DELETE_TODO_ITEM
  fields:
    item:
      required: true
      selector:
        text:
