# Describes the format for available cover services

open_cover:
  name: Open
  description: Open all or specified cover.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.OPEN

close_cover:
  name: Close
  description: Close all or specified cover.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.CLOSE

toggle:
  name: Toggle
  description: Toggle a cover open/closed.
  target:
    entity:
      domain: cover
      supported_features:
        - - cover.CoverEntityFeature.CLOSE
          - cover.CoverEntityFeature.OPEN

set_cover_position:
  name: Set position
  description: Move to specific position all or specified cover.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.SET_POSITION
  fields:
    position:
      name: Position
      description: Position of the cover
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

stop_cover:
  name: Stop
  description: Stop all or specified cover.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.STOP

open_cover_tilt:
  name: Open tilt
  description: Open all or specified cover tilt.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.OPEN_TILT

close_cover_tilt:
  name: Close tilt
  description: Close all or specified cover tilt.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.CLOSE_TILT

toggle_cover_tilt:
  name: Toggle tilt
  description: Toggle a cover tilt open/closed.
  target:
    entity:
      domain: cover
      supported_features:
        - - cover.CoverEntityFeature.CLOSE_TILT
          - cover.CoverEntityFeature.OPEN_TILT

set_cover_tilt_position:
  name: Set tilt position
  description: Move to specific position all or specified cover tilt.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.SET_TILT_POSITION
  fields:
    tilt_position:
      name: Tilt position
      description: Tilt position of the cover.
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

stop_cover_tilt:
  name: Stop tilt
  description: Stop all or specified cover.
  target:
    entity:
      domain: cover
      supported_features:
        - cover.CoverEntityFeature.STOP_TILT
