# Describes the format for available alarm control panel services

alarm_disarm:
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_arm_custom_bypass:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_arm_home:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_HOME
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_arm_away:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_AWAY
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_arm_night:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_NIGHT
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_arm_vacation:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.ARM_VACATION
  fields:
    code:
      example: "1234"
      selector:
        text:

alarm_trigger:
  target:
    entity:
      domain: alarm_control_panel
      supported_features:
        - alarm_control_panel.AlarmControlPanelEntityFeature.TRIGGER
  fields:
    code:
      example: "1234"
      selector:
        text:
