# Describes the format for available motion blinds services

set_absolute_position:
  target:
    entity:
      integration: motion_blinds
      domain: cover
  fields:
    absolute_position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    tilt_position:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    width:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
