snapshot:
  name: Snapshot
  description: Take a snapshot of the media player zone.
  target:
    entity:
      integration: ws66i
      domain: media_player

restore:
  name: Restore
  description: Restore a snapshot of the media player zone.
  target:
    entity:
      integration: ws66i
      domain: media_player
