# ScreenLogic Services
set_color_mode:
  target:
    device:
      integration: screenlogic
  fields:
    color_mode:
      required: true
      selector:
        select:
          options:
            - all_off
            - all_on
            - american
            - blue
            - caribbean
            - color_set
            - color_swim
            - color_sync
            - green
            - hold
            - magenta
            - next_mode
            - party
            - recall
            - red
            - reset
            - romance
            - royal
            - save
            - sunset
            - thumper
            - white
