open_commissioning_window:
  name: Open Commissioning Window
  description: >
    Allow adding one of your devices to another Matter network by opening the commissioning window for this Matter device for 60 seconds.
  fields:
    device_id:
      name: Device
      description: The Matter device to add to the other Matter network.
      required: true
      selector:
        device:
          integration: matter
