set_time_to:
  name: Set Time To
  description: Control timers to turn the system on or off after a set number of minutes
  target:
    entity:
      integration: advantage_air
      domain: sensor
  fields:
    minutes:
      name: Minutes
      description: Minutes until action
      required: true
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: minutes
