check_config:
reload_core_config:
restart:
set_location:
  fields:
    latitude:
      required: true
      example: 32.87336
      selector:
        text:
    longitude:
      required: true
      example: 117.22743
      selector:
        text:

stop:
toggle:
  target:
    entity: {}

turn_on:
  target:
    entity: {}

turn_off:
  target:
    entity: {}

update_entity:
  target:
    entity: {}

reload_custom_templates:
reload_config_entry:
  target:
    entity: {}
    device: {}
  fields:
    entry_id:
      advanced: true
      required: false
      example: 8955375327824e14ba89e4b29cc3ec9a
      selector:
        text:

save_persistent_states:
