# Describes the format for available Nest services

set_away_mode:
  fields:
    away_mode:
      required: true
      selector:
        select:
          options:
            - "away"
            - "home"
    structure:
      example: "Apartment"
      selector:
        object:

set_eta:
  fields:
    eta:
      required: true
      selector:
        time:
    eta_window:
      default: "00:01"
      selector:
        time:
    trip_id:
      example: "Leave Work"
      selector:
        text:
    structure:
      example: "Apartment"
      selector:
        object:

cancel_eta:
  fields:
    trip_id:
      required: true
      example: "Leave Work"
      selector:
        text:
    structure:
      example: "Apartment"
      selector:
        object:
