calibrate:
  name: Calibrate
  description: Calibration - Set depth, press & hold duration, and operation mode. Warning - this will send a push command to the device
  fields:
    entity_id:
      name: Entity
      description: Name of entity to calibrate
      selector:
        entity:
          integration: keymitt_ble
          domain: switch
    depth:
      name: Depth
      description: Depth in percent
      example: 50
      required: true
      selector:
        number:
          mode: slider
          step: 1
          min: 0
          max: 100
          unit_of_measurement: "%"
    duration:
      name: Duration
      description: Duration in seconds
      example: 1
      required: true
      selector:
        number:
          mode: box
          step: 1
          min: 0
          max: 60
          unit_of_measurement: seconds
    mode:
      name: Mode
      description: normal | invert | toggle
      example: "normal"
      required: true
      selector:
        select:
          options:
            - "normal"
            - "invert"
            - "toggle"
