select_first:
  name: First
  description: Select the first option of an select entity.
  target:
    entity:
      domain: select

select_last:
  name: Last
  description: Select the last option of an select entity.
  target:
    entity:
      domain: select

select_next:
  name: Next
  description: Select the next options of an select entity.
  target:
    entity:
      domain: select
  fields:
    cycle:
      name: Cycle
      description: If the option should cycle from the last to the first.
      default: true
      selector:
        boolean:

select_option:
  name: Select
  description: Select an option of an select entity.
  target:
    entity:
      domain: select
  fields:
    option:
      name: Option
      description: Option to be selected.
      required: true
      example: '"Item A"'
      selector:
        text:

select_previous:
  name: Previous
  description: Select the previous options of an select entity.
  target:
    entity:
      domain: select
  fields:
    cycle:
      name: Cycle
      description: If the option should cycle from the first to the last.
      default: true
      selector:
        boolean:
