send_poi:
  name: Send POI
  description: Send a GPS location to the vehicle's navigation system as a POI (Point of Interest). Requires a navigation SD card installed in the vehicle.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to send the GPS location to
      required: true
      selector:
        device:
          integration: mazda
    latitude:
      name: Latitude
      description: The latitude of the location to send
      example: 12.34567
      required: true
      selector:
        number:
          min: -90
          max: 90
          unit_of_measurement: °
          mode: box
    longitude:
      name: Longitude
      description: The longitude of the location to send
      example: -34.56789
      required: true
      selector:
        number:
          min: -180
          max: 180
          unit_of_measurement: °
          mode: box
    poi_name:
      name: POI name
      description: A friendly name for the location
      example: Work
      required: true
      selector:
        text:
