get_prices:
  fields:
    type:
      required: true
      example: "gas"
      selector:
        select:
          options:
            - "gas"
            - "energy"
    incl_vat:
      required: false
      example: false
      selector:
        boolean:
    start:
      required: false
      example: "2023-01-01 00:00:00"
      selector:
        datetime:
    end:
      required: false
      example: "2023-01-01 00:00:00"
      selector:
        datetime:
