sync_clock:
  name: Sync clock
  description: Sync the velbus modules clock to the Home Assistant clock, this is the same as the 'sync clock' from VelbusLink
  fields:
    interface:
      name: Interface
      description: The velbus interface to send the command to, this will be the same value as used during configuration
      required: true
      example: "192.168.1.5:27015"
      default: ""
      selector:
        text:

scan:
  name: Scan
  description: Scan the velbus modules, this will be need if you see unknown module warnings in the logs, or when you added new modules
  fields:
    interface:
      name: Interface
      description: The velbus interface to send the command to, this will be the same value as used during configuration
      required: true
      example: "192.168.1.5:27015"
      default: ""
      selector:
        text:

clear_cache:
  name: Clear cache
  description: Clears the velbuscache and then starts a new scan
  fields:
    interface:
      name: Interface
      description: The velbus interface to send the command to, this will be the same value as used during configuration
      required: true
      example: "192.168.1.5:27015"
      default: ""
      selector:
        text:
    address:
      name: Address
      description: >
        The module address in decimal format, if this is provided we only clear this module, if nothing is provided we clear the whole cache directory (all modules)
        The decimal addresses are displayed in front of the modules listed at the integration page.
      required: false
      selector:
        number:
          min: 1
          max: 254

set_memo_text:
  name: Set memo text
  description: >
    Set the memo text to the display of modules like VMBGPO, VMBGPOD
    Be sure the page(s) of the module is configured to display the memo text.
  fields:
    interface:
      name: Interface
      description: The velbus interface to send the command to, this will be the same value as used during configuration
      required: true
      example: "192.168.1.5:27015"
      default: ""
      selector:
        text:
    address:
      name: Address
      description: >
        The module address in decimal format.
        The decimal addresses are displayed in front of the modules listed at the integration page.
      required: true
      selector:
        number:
          min: 1
          max: 254
    memo_text:
      name: Memo text
      description: >
        The actual text to be displayed.
        Text is limited to 64 characters.
      example: "Do not forget trash"
      default: ""
      selector:
        text:
