set_aircleaner_mode:
  name: Set air cleaner mode
  description: "The air cleaner mode."
  target:
    entity:
      integration: nexia
      domain: climate
  fields:
    aircleaner_mode:
      name: Air cleaner mode
      description: "The air cleaner mode to set."
      required: true
      selector:
        select:
          options:
            - "allergy"
            - "auto"
            - "quick"

set_humidify_setpoint:
  name: Set humidify set point
  description: "The humidification set point."
  target:
    entity:
      integration: nexia
      domain: climate
  fields:
    humidity:
      name: Humidify
      description: "The humidification setpoint."
      required: true
      selector:
        number:
          min: 35
          max: 65
          unit_of_measurement: "%"

set_hvac_run_mode:
  name: Set hvac run mode
  description: "The hvac run mode."
  target:
    entity:
      integration: nexia
      domain: climate
  fields:
    run_mode:
      name: Run mode
      description: "Run the schedule or hold. If not specified, the current run mode will be used."
      required: false
      selector:
        select:
          options:
            - "permanent_hold"
            - "run_schedule"
    hvac_mode:
      name: Hvac mode
      description: "The hvac mode to use for the schedule or hold. If not specified, the current hvac mode will be used."
      required: false
      selector:
        select:
          options:
            - "auto"
            - "cool"
            - "heat"
