# Describes the format for available Blink services

blink_update:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: blink

trigger_camera:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: blink

save_video:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: blink
    name:
      required: true
      example: "Living Room"
      selector:
        text:
    filename:
      required: true
      example: "/tmp/video.mp4"
      selector:
        text:

save_recent_clips:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: blink
    name:
      required: true
      example: "Living Room"
      selector:
        text:
    file_path:
      required: true
      example: "/tmp"
      selector:
        text:

send_pin:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: blink
    pin:
      example: "abc123"
      selector:
        text:
