# Describes the format for available Blink services

blink_update:
trigger_camera:
  target:
    entity:
      integration: blink
      domain: camera

save_video:
  fields:
    name:
      required: true
      example: "Living Room"
      selector:
        text:
    filename:
      required: true
      example: "/tmp/video.mp4"
      selector:
        text:

save_recent_clips:
  fields:
    name:
      required: true
      example: "Living Room"
      selector:
        text:
    file_path:
      required: true
      example: "/tmp"
      selector:
        text:

send_pin:
  fields:
    pin:
      example: "abc123"
      selector:
        text:
