# Describes the format for available recorder services

purge:
  fields:
    keep_days:
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days

    repack:
      default: false
      selector:
        boolean:

    apply_filter:
      default: false
      selector:
        boolean:

purge_entities:
  target:
    entity: {}
  fields:
    domains:
      example: "sun"
      required: false
      default: []
      selector:
        object:

    entity_globs:
      example: "domain*.object_id*"
      required: false
      default: []
      selector:
        object:

    keep_days:
      default: 0
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days

disable:
enable:
