# Describes the format for available recorder services

purge:
  name: Purge
  description: Start purge task - to clean up old data from your database.
  fields:
    keep_days:
      name: Days to keep
      description: Number of history days to keep in database after purge.
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days

    repack:
      name: Repack
      description: Attempt to save disk space by rewriting the entire database file.
      default: false
      selector:
        boolean:

    apply_filter:
      name: Apply filter
      description: Apply entity_id and event_type filter in addition to time based purge.
      default: false
      selector:
        boolean:

purge_entities:
  name: Purge Entities
  description: Start purge task to remove specific entities from your database.
  target:
    entity: {}
  fields:
    domains:
      name: Domains to remove
      description: List the domains that need to be removed from the recorder database.
      example: "sun"
      required: false
      default: []
      selector:
        object:

    entity_globs:
      name: Entity Globs to remove
      description: List the glob patterns to select entities for removal from the recorder database.
      example: "domain*.object_id*"
      required: false
      default: []
      selector:
        object:

    keep_days:
      name: Days to keep
      description: Number of history days to keep in database of matching rows. The default of 0 days will remove all matching rows.
      default: 0
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days

disable:
  name: Disable
  description: Stop the recording of events and state changes

enable:
  name: Enable
  description: Start the recording of events and state changes
