load_url:
  name: Load URL
  description: Load a URL on Fully Kiosk Browser
  target:
    device:
      integration: fully_kiosk
  fields:
    url:
      name: URL
      description: URL to load.
      example: "https://home-assistant.io"
      required: true
      selector:
        text:
