send_text_command:
  name: Send text command
  description: Send a command as a text query to Google Assistant.
  fields:
    command:
      name: Command
      description: Command to send to Google Assistant.
      example: turn off kitchen TV
      selector:
        text:
