set_watering_time:
  name: Set watering time
  description: Sets time for watering
  target:
  fields:
    watering_time:
      name: Duration
      description: Duration for this irrigation to be turned on.
      example: 30
set_pause_time:
  name: Set pause time
  description: Sets time to pause.
  target:
  fields:
    pause_time:
      name: Duration
      description: Duration for this irrigation to be paused.
      example: 24
set_trigger:
  name: Set trigger
  description: Set the trigger to use.
  target:
  fields:
    trigger_index:
      name: Trigger index
      description: Index of Trigger from 1 to 4
      example: "1"
    trigger:
      name: Trigger rules
      description: Configuration of trigger.
      example: "'12707001'"
