# Describes the format for available services for ambiclimate

set_comfort_mode:
  fields:
    name:
      required: true
      example: Bedroom
      selector:
        text:

send_comfort_feedback:
  fields:
    name:
      required: true
      example: Bedroom
      selector:
        text:
    value:
      required: true
      example: bit_warm
      selector:
        text:

set_temperature_mode:
  fields:
    name:
      required: true
      example: Bedroom
      selector:
        text:
    value:
      required: true
      example: 22
      selector:
        text:
