set_default_level:
  name: Set default level
  description: Set the default log level for integrations.
  fields:
    level:
      name: Level
      description: Default severity level for all integrations.
      selector:
        select:
          options:
            - label: "Debug"
              value: "debug"
            - label: "Info"
              value: "info"
            - label: "Warning"
              value: "warning"
            - label: "Error"
              value: "error"
            - label: "Fatal"
              value: "fatal"
            - label: "Critical"
              value: "critical"

set_level:
  name: Set level
  description: Set log level for integrations.
